### ISSUE TITLE
NPE on cross dimensional teleport

### ISSUE THREAD

**Issue by cjm721** [MoreThanHidden/RestrictedPortals#13]
Teleported from an rftools dimension to nether.

Version 1.12-0.6.1
Forge: 2484

```
[00:40:22] [Server thread/WARN]: Failed to handle packet for /73.222.0.7:57633
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.Teleporter.func_180620_b(SourceFile:128) ~[anc.class:?]
        at net.minecraft.world.Teleporter.func_180266_a(SourceFile:65) ~[anc.class:?]
        at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:707) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:617) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.func_187242_a(PlayerList.java:604) ~[pl.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:695) ~[oq.class:?]
        at morethanhidden.restrictedportals.handlers.TickHandler.onPlayerTickEvent(TickHandler.java:49) ~[TickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1306_TickHandler_onPlayerTickEvent_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:376) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:286) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
```

**Comment by MoreThanHidden** [comment]
I failed to make a nether portal in RFTools Dimensions anyway, but if possible the crash shouldn't be on my end now.

Let me know if your still having issues.

**Comment by cjm721** [comment]
Will have a check when pack updates. I used RT Tool teleport along with FTB Utilities to get from other dimension to nether.
