### ISSUE TITLE
[1.13] Client crash due to missing config

### ISSUE THREAD

**Issue by MoreThanHidden** [MoreThanHidden/RestrictedPortals#19]
Client crashes when trying to join a server:
Forge version: 25.0.10
Probably fixed in forge 25.0.13

`java.lang.NullPointerException: Cannot get config value without assigned Config object present
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at net.minecraftforge.common.ForgeConfigSpec$ConfigValue.get(ForgeConfigSpec.java:595)
	at net.minecraft.world.World.tickEntities(World.java:1087)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1198)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:772)
	at net.minecraft.client.Minecraft.run(Minecraft.java:358)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)`

**Comment by MoreThanHidden** [comment]
Fixed in Forge 25.0.13
