### ISSUE TITLE
Possible Crash / Not working with 1.14.3

### ISSUE THREAD

**Issue by MoreThanHidden** [MoreThanHidden/RestrictedPortals#21]

**Comment by MoreThanHidden** [comment]
`java.lang.NullPointerException: Ticking player
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:323) ~[?:?] {}
	at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:316) ~[?:?] {}
	at morethanhidden.restrictedportals.handlers.EventHandler.onPlayerChangeDim(EventHandler.java:28) ~[?:1.14.3-0.9] {}
	at net.minecraftforge.eventbus.ASMEventHandler_1_EventHandler_onPlayerChangeDim_EntityTravelToDimensionEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onTravelToDimension(ForgeHooks.java:723) ~[?:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_212321_a(ServerPlayerEntity.java:575) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_213284_aV(Entity.java:1774) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:383) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:270) ~[?:?] {}
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:364) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1956) ~[?:?] {}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:218) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:240) ~[?:?] {}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:830) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}`

**Comment by MoreThanHidden** [comment]
Only happens when other mods corrupt the game data.
