### ISSUE TITLE
InvalidInjectionException on Fabric Server [1.19.3]

### ISSUE THREAD

**Issue by MrRubberDucky** [MoreThanHidden/RestrictedPortals#37]
Tested on a clean server instance of Fabric 1.19.3 with just RestrictedPortals 1.4.3 and latest Fabric API

```[13:25:37] [main/WARN]: Reference map 'restrictedportals.refmap.json' for restrictedportals.mixins.json could not be read. If this is a development environment you can ignore this message
[13:25:41] [main/INFO]: Building unoptimized datafixer
[13:25:41] [main/ERROR]: Mixin apply for mod restrictedportals failed restrictedportals.mixins.json:ServerPlayerMixin from mod restrictedportals -> net.minecraft.class_3222: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on injected could not find any targets matching 'changeDimension(Lnet/minecraft/server/level/ServerLevel;)Lnet/minecraft/world/entity/Entity;' in net.minecraft.class_3222. No refMap loaded. [PREINJECT Applicator Phase -> restrictedportals.mixins.json:ServerPlayerMixin from mod restrictedportals -> Prepare Injections ->  -> handler$zgc000$injected(Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injected could not find any targets matching 'changeDimension(Lnet/minecraft/server/level/ServerLevel;)Lnet/minecraft/world/entity/Entity;' in net.minecraft.class_3222. No refMap loaded. [PREINJECT Applicator Phase -> restrictedportals.mixins.json:ServerPlayerMixin from mod restrictedportals -> Prepare Injections ->  -> handler$zgc000$injected(Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4149.<clinit>(class_4149.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_7110.<clinit>(class_7110.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:887) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1155) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.1]
[13:25:41] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.1]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.minecraft.class_4149.<clinit>(class_4149.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_7110.<clinit>(class_7110.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:887) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1155) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4149.<clinit>(class_4149.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_7110.<clinit>(class_7110.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:887) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1155) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4149.<clinit>(class_4149.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_7110.<clinit>(class_7110.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:887) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1155) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [restrictedportals.mixins.json:ServerPlayerMixin from mod restrictedportals] from phase [DEFAULT] in config [restrictedportals.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4149.<clinit>(class_4149.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_7110.<clinit>(class_7110.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:887) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1155) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injected could not find any targets matching 'changeDimension(Lnet/minecraft/server/level/ServerLevel;)Lnet/minecraft/world/entity/Entity;' in net.minecraft.class_3222. No refMap loaded. [PREINJECT Applicator Phase -> restrictedportals.mixins.json:ServerPlayerMixin from mod restrictedportals -> Prepare Injections ->  -> handler$zgc000$injected(Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4149.<clinit>(class_4149.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_7110.<clinit>(class_7110.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:887) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1155) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 4 more```

**Comment by MoreThanHidden** [comment]
Thanks for reporting, can see the issue and a few more will fix that up.
Not sure why I didn't test on a Fabric Server 😅
